### ISSUE TITLE
Crashes every time when README.md isn't valid markdown

### ISSUE THREAD

**Issue by aschekatihin** [paprikka/lana-cli#10]
```
TypeError: Cannot read property 'references' of undefined
    at Array.link (C:\Users\andrew\AppData\Roaming\npm\node_modules\lana-cli\node_modules\markdown-it\lib\rules_inline\link.js:101:26)
    at ParserInline.tokenize (C:\Users\andrew\AppData\Roaming\npm\node_modules\lana-cli\node_modules\markdown-it\lib\parser_inline.js:135:22)
    at ParserInline.parse (C:\Users\andrew\AppData\Roaming\npm\node_modules\lana-cli\node_modules\markdown-it\lib\parser_inline.js:163:8)
    at Array.inline (C:\Users\andrew\AppData\Roaming\npm\node_modules\lana-cli\node_modules\markdown-it\lib\rules_core\inline.js:10:23)
    at Core.process (C:\Users\andrew\AppData\Roaming\npm\node_modules\lana-cli\node_modules\markdown-it\lib\parser_core.js:51:13)
    at MarkdownIt.parse (C:\Users\andrew\AppData\Roaming\npm\node_modules\lana-cli\node_modules\markdown-it\lib\index.js:523:13)
    at md2json (C:\Users\andrew\AppData\Roaming\npm\node_modules\lana-cli\src\md2json.js:5:23)
```
In my case there was incorrectly formatted JSON in readme.

Sample JSON to reproduce (could be the only line in readme):
```
[{"user_id":"xxx","email":"yyy","name":"zzz","nickname":"zzz","created_at":"2020-02-20T15:20:22.260Z","updated_at":"2020-02-20T15:20:22.260Z","email_verified":true}]
```

So obviously it could be fixed by adding tripple ticks to quote as code block in readme.md.
But it would be nice to just have a warning and skip parsing of readme in that case.

**Comment by paprikka** [comment]
Hej, this should be available in the current version. Thanks for the feedback!
